server:
  port: 8040
  undertow:
    io-threads: 8
    worker-threads: 64
    direct-buffers: true
    buffer-size: 16384
    buffers-per-region: 40

zuul:
  ignored-services: hystrix-monitor,sleuth-server
  host:
    maxTotalConnections: 500
    maxPerRouteConnections: 45
  semaphore:
    max-semaphores: 128

spring:
  application:
    name: "api-gateway"
  jackson:
    serialization:
      indent_output: true
  http:
    multipart:
      max-file-size: 2048Mb
      max-request-size: 2048Mb

hystrix:
  threadpool:
    default:
      coreSize: 25
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

feign:
  hystrix:
    enabled: true

filter:
  userManager:
    id: reception-center
    tokenName: access-token
  whiteList: /${filter.userManager.id}/member/signIn,/${filter.userManager.id}/member/who,/file-system/v1/fs/preview/
  monitorManager:
    id: monitor-center
  format:
    header: Accept
    defaultWay: application/json;charset=utf-8

info:
  app:
    name: ${spring.application.name}
    version: v3.0
    time: 2017年9月12日21:55:00
  describe: "soa api前置网关，负责进行服务访问鉴权，保证各个SOA由外部访问内部的服务组件安全。"
  home: /
  author: afterloe.L
  licensed: MIT Licensed

developer:
  name: user
  password: register

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    nonSecurePort: ${server.port:8080}
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://${developer.name}:${developer.password}@172.19.192.1:8761/eureka/,http://${developer.name}:${developer.password}@172.19.193.1:8761/eureka/,http://${developer.name}:${developer.password}@172.19.194.1:8761/eureka/